CREATE TABLE SYS.ENROLLEE(
ID INT primary KEY AUTO_INCREMENT,
NAME VARCHAR(30),
ACTIVATION_STATUS boolean,
BIRTH_DATE DATE,
PHONE_NUMBER varchar(15)
);
DROP TABLE SYS.DEPENDENT;
CREATE TABLE SYS.DEPENDENT(
ID INT primary KEY AUTO_INCREMENT,
NAME VARCHAR(30),
BIRTH_DATE DATE,
ENROLLEE_ID INT, 
FOREIGN KEY (ENROLLEE_ID) references SYS.ENROLLEE(ID)
);

commit;